### ISSUE TITLE
Any plans for unpublish support

### ISSUE THREAD

**Issue by jesustalaveragomez** [contentful/contentful-scheduler.rb#10]
Hi,

I wonder if have you planned to add support for scheduled unpublishing.

Thank you.
Regards

**Comment by dlitvakb** [comment]
Sounds like a good idea.

I'll add it to my backlog, and discuss it as soon as possible with my team.

Look forward to a new release within this month 😄 

Cheers

**Comment by dlitvakb** [comment]
This has been released in version `0.5.0`.

Cheers
