### ISSUE TITLE
Unpublisher Randomly Fails.

### ISSUE THREAD

**Issue by john007abhilash** [contentful/contentful-scheduler.rb#15]
I was testing the unpublisher, it worked only 3 out of 10 times while i was testing it. I checked the redis DB the enteries go in the unpublish queue successfully all the times and they are removed out of the queue when the unpublish time has reached sucessfully all the the times but the pages does not get unpublished.

Also i always get this in my logs 
"08:36:49 web.1              | W, [2018-07-30T08:36:49.265704#14]  WARN -- : Webhook {id: XXXXXXXXX, space_id: XXXXXX} couldn't be added to the unpublish queue"

What i figured out is why is this sucess variable of publish(https://github.com/contentful/contentful-scheduler.rb/blob/master/lib/contentful/scheduler/queue.rb#L18) is being used in unpublish condition https://github.com/contentful/contentful-scheduler.rb/blob/master/lib/contentful/scheduler/queue.rb#L23

**Comment by dlitvakb** [comment]
Hey @john007abhilash,

I will remove the dependant success check, as the unpublishing action is not limited by the success of the publish action. That said, the enqueueing itself should not be affected, and the event should be triggered.

I will also check about the unpublishing action not working properly.

Cheers

**Comment by dlitvakb** [comment]
Heyy @john007abhilash,

I didn't find the action not triggering, but indeed found that the success check there was unnecessary. This is now waiting for a peer review and will be merged and released as soon as that's done.

Cheers

**Comment by dlitvakb** [comment]
This has just been released as 0.5.1

Cheers

**Comment by john007abhilash** [comment]
Hey @dlitvakb sorry to say the issue still persists.

**Comment by dlitvakb** [comment]
Hey @john007abhilash,

Could you provide a bit more context? On my own spaces I haven't had any issues, both publishing and unpublishing worked in multiple scenarios.

Cheers

**Comment by john007abhilash** [comment]
Hey @dlitvakb can you share your Gemfile, for me it looks like. Just to be sure we are on the same page.

source 'https://rubygems.org'

gem 'contentful-scheduler', '~> 0.5.1'
gem 'contentful-management', '~> 1.0'
gem 'resque', '~> 1.0'
gem 'resque-scheduler', '4.2.1'
gem 'rake'
gem 'foreman', '~> 0.84.0'
gem 'redis', '~> 3.0'
gem 'chronic', '~> 0.10'
