### ISSUE TITLE
Contentful Scheduler not publishing enteries

### ISSUE THREAD

**Issue by john007abhilash** [contentful/contentful-scheduler.rb#5]
I have a created a webhook and scheduler on a public server accessible from contenful.
Attaching contentful scheduler logs, also to my understanding, scheduler is able to listen to webhook calls broadcasted from contentful and it is able queue the job, but not publish it. 

12:59:52 resque_scheduler.1 | resque-scheduler: [INFO] 2017-12-18T12:59:52+02:00: Schedule empty! Set Resque.schedule
12:59:52 resque_scheduler.1 | resque-scheduler: [INFO] 2017-12-18T12:59:52+02:00: Schedules Loaded
12:59:52 resque_scheduler.1 | Passing 'info' command to redis as is; administrative commands cannot be effectively namespaced and should be called on the redis connection directly; passthrough has been deprecated and will be removed in redis-namespace 2.0 (at /home/sdc-user/.rvm/gems/ruby-2.4.2/gems/resque-1.27.4/lib/resque/data_store.rb:59:in `method_missing')
12:59:52 web.1              | I, [2017-12-18T12:59:52.564470 #2710]  INFO -- : Webhook server starting at: http://0.0.0.0:32123
12:59:52 web.1              | I, [2017-12-18T12:59:52.564940 #2710]  INFO -- : Available Endpoints:
12:59:52 web.1              | I, [2017-12-18T12:59:52.565126 #2710]  INFO -- : 	/scheduler - Controller: Contentful::Scheduler::Controller - Timeout: 0
12:59:52 resque_scheduler.1 | Passing 'script' command to redis as is; administrative commands cannot be effectively namespaced and should be called on the redis connection directly; passthrough has been deprecated and will be removed in redis-namespace 2.0 (at /home/sdc-user/.rvm/gems/ruby-2.4.2/gems/resque-1.27.4/lib/resque/data_store.rb:59:in `method_missing')
12:59:57 resque_scheduler.1 | Passing 'script' command to redis as is; administrative commands cannot be effectively namespaced and should be called on the redis connection directly; passthrough has been deprecated and will be removed in redis-namespace 2.0 (at /home/sdc-user/.rvm/gems/ruby-2.4.2/gems/resque-1.27.4/lib/resque/data_store.rb:59:in `method_missing')
13:01:00 web.1              | D, [2017-12-18T13:01:00.145774 #2710] DEBUG -- : Webhook Data: {id: XXXXXXXXXXXX, space_id: XXXXXXXX, kind: Entry, event: auto_save}
13:01:00 web.1              | I, [2017-12-18T13:01:00.146155 #2710]  INFO -- : Queueing - Space: XXXXXX - Entry: XXXXXXXXXXXX

**Comment by dlitvakb** [comment]
Hey @john007abhilash,

Looks like your entry was already published before, this gem currently does not re-publish content.

I'll add that feature in, I'll let you know as soon as a release is made.

Cheers

**Comment by dlitvakb** [comment]
This has been released.
